name: Publish NuGet packages (Mac)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Mac-NuGet-Builds:
    env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_TOKEN}}
      DOTNET_NOLOGO: true

    runs-on: macos-latest
    steps:
    - name: Clone source
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - name: "Restore NuGet packages (Mac)"
      run: msbuild /t:restore /p:Configuration=Release Sources/Microcharts-mac.slnf /v:diag /bl:mac-build.binlog

    - name: "Publish bin logs as artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: msbuild-binlogs
        path: '**/*.binlog'
      if: always()

    - name: "Build and pack Microcharts macOS"
      run: msbuild /t:build,pack /p:Configuration=Release Sources/Microcharts.macOS/Microcharts.macOS.csproj

    - name: Publish packages to nuget.org
      run: |
        cd artifacts
        ls *.nupkg
        nuget push "*.nupkg" -SkipDuplicate -NoSymbols -ApiKey $NUGET_AUTH_TOKEN -Source https://api.nuget.org/v3/index.json
